import { ArrowDown, ArrowUp, Plus } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { ApiError, apiFetch } from '../../lib/api';
import { KgdEmpty, KgdModal, KgdPage, KgdStatus, money } from '../components';

type Category={id:string;slug:string;name:string;description:string;active:boolean;sort_order:number};
type Service={id:string;category_id:string;category_name:string;category_slug:string;slug:string;name:string;short_name:string;description:string;price_pence:number;duration_minutes:number;is_add_on:boolean;featured:boolean;accepts_add_ons:boolean;allows_product_removal:boolean;compatible_category_slugs:string[];finder_tags:string[];active:boolean;sort_order:number};

export function ServicesPage(){
  const [categories,setCategories]=useState<Category[]>([]);const [services,setServices]=useState<Service[]>([]);const [selected,setSelected]=useState<Service|null>(null);const [createOpen,setCreateOpen]=useState(false);const [categoryOpen,setCategoryOpen]=useState(false);const [error,setError]=useState('');
  async function load(){try{const result=await apiFetch<{categories:Category[];services:Service[]}>('/api/admin/services');setCategories(result.categories);setServices(result.services);}catch(requestError){setError(requestError instanceof ApiError?requestError.message:'Services could not be loaded.');}}
  useEffect(()=>{void load();},[]);
  async function toggle(service:Service){try{await apiFetch(`/api/admin/services/${service.id}`,{method:'PATCH',body:JSON.stringify({active:!service.active})});await load();}catch(requestError){setError(requestError instanceof ApiError?requestError.message:'Service could not be updated.');}}
  async function move(service:Service,direction:number){const ordered=[...services];const index=ordered.findIndex((item)=>item.id===service.id);const target=index+direction;if(target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];await apiFetch('/api/admin/services/reorder',{method:'POST',body:JSON.stringify({items:ordered.map((item,sortOrder)=>({id:item.id,sortOrder}))})});await load();}
  return <KgdPage eyebrow="PUBLIC MENU" title="Services" actions={<><button className="kgd-button" type="button" onClick={()=>setCategoryOpen(true)}>New category</button><button className="kgd-button is-primary" type="button" onClick={()=>setCreateOpen(true)}><Plus size={16}/>New service</button></>}>
    {error?<KgdStatus message={error} error/>:null}
    <section className="kgd-table-shell"><table className="kgd-table"><thead><tr><th>Order</th><th>Service</th><th>Category</th><th>Duration</th><th>Price</th><th>Type</th><th>Status</th><th></th></tr></thead><tbody>{services.map((service,index)=><tr key={service.id}><td><div className="kgd-order"><button className="kgd-icon-button" type="button" title="Move up" disabled={index===0} onClick={()=>void move(service,-1)}><ArrowUp size={15}/></button><button className="kgd-icon-button" type="button" title="Move down" disabled={index===services.length-1} onClick={()=>void move(service,1)}><ArrowDown size={15}/></button></div></td><td><strong>{service.name}</strong><small>{service.description}</small></td><td>{service.category_name}</td><td>{service.duration_minutes} min</td><td>{money(service.price_pence)}</td><td>{service.is_add_on?'Add-on':'Treatment'}</td><td><button className={`kgd-toggle ${service.active?'is-on':''}`} type="button" aria-pressed={service.active} onClick={()=>void toggle(service)}><span/>{service.active?'Active':'Inactive'}</button></td><td><button className="kgd-text-button" type="button" onClick={()=>setSelected(service)}>Edit</button></td></tr>)}</tbody></table>{!services.length?<KgdEmpty>No services yet.</KgdEmpty>:null}</section>
    {(createOpen||selected)?<ServiceForm service={selected??undefined} categories={categories} onClose={()=>{setCreateOpen(false);setSelected(null);}} onSaved={async()=>{setCreateOpen(false);setSelected(null);await load();}}/>:null}
    {categoryOpen?<CategoryForm onClose={()=>setCategoryOpen(false)} onSaved={async()=>{setCategoryOpen(false);await load();}}/>:null}
  </KgdPage>;
}

function ServiceForm({service,categories,onClose,onSaved}:{service?:Service;categories:Category[];onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({categoryId:service?.category_id??categories[0]?.id??'',name:service?.name??'',shortName:service?.short_name??'',description:service?.description??'',price:String((service?.price_pence??0)/100),durationMinutes:String(service?.duration_minutes??45),isAddOn:service?.is_add_on??false,featured:service?.featured??false,acceptsAddOns:service?.accepts_add_ons??false,allowsProductRemoval:service?.allows_product_removal??false,compatibleCategorySlugs:service?.compatible_category_slugs??[],finderTags:(service?.finder_tags??[]).join(', '),active:service?.active??true});const [message,setMessage]=useState('');
  async function submit(event:FormEvent){event.preventDefault();const body={...form,pricePence:Math.round(Number(form.price)*100),durationMinutes:Number(form.durationMinutes),finderTags:form.finderTags.split(',').map((item)=>item.trim()).filter(Boolean)};delete (body as {price?:string}).price;try{await apiFetch(service?`/api/admin/services/${service.id}`:'/api/admin/services',{method:service?'PATCH':'POST',body:JSON.stringify(body)});onSaved();}catch(error){setMessage(error instanceof ApiError?error.message:'Service could not be saved.');}}
  return <KgdModal title={service?`Edit ${service.name}`:'New service'} onClose={onClose} wide><form className="kgd-form" onSubmit={submit}><div className="kgd-form-grid"><label><span>Category</span><select value={form.categoryId} onChange={(event)=>setForm({...form,categoryId:event.target.value})}>{categories.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span>Name</span><input value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} required/></label><label><span>Short name</span><input value={form.shortName} onChange={(event)=>setForm({...form,shortName:event.target.value})} required/></label><label><span>Price (£)</span><input type="number" min="0" step="0.01" value={form.price} onChange={(event)=>setForm({...form,price:event.target.value})}/></label><label><span>Duration (minutes)</span><input type="number" min="5" step="5" value={form.durationMinutes} onChange={(event)=>setForm({...form,durationMinutes:event.target.value})}/></label><label><span>Finder tags, comma separated</span><input value={form.finderTags} onChange={(event)=>setForm({...form,finderTags:event.target.value})}/></label></div><label><span>Description</span><textarea value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})}/></label><fieldset className="kgd-check-group"><legend>Service behaviour</legend><label><input type="checkbox" checked={form.isAddOn} onChange={(event)=>setForm({...form,isAddOn:event.target.checked})}/>Add-on</label><label><input type="checkbox" checked={form.featured} onChange={(event)=>setForm({...form,featured:event.target.checked})}/>Featured publicly</label><label><input type="checkbox" checked={form.acceptsAddOns} onChange={(event)=>setForm({...form,acceptsAddOns:event.target.checked})}/>Accepts add-ons</label><label><input type="checkbox" checked={form.allowsProductRemoval} onChange={(event)=>setForm({...form,allowsProductRemoval:event.target.checked})}/>Allows product removal</label><label><input type="checkbox" checked={form.active} onChange={(event)=>setForm({...form,active:event.target.checked})}/>Active</label></fieldset>{form.isAddOn?<fieldset className="kgd-check-group"><legend>Compatible categories</legend>{categories.filter((category)=>category.slug!=='addons').map((category)=><label key={category.id}><input type="checkbox" checked={form.compatibleCategorySlugs.includes(category.slug)} onChange={()=>setForm({...form,compatibleCategorySlugs:form.compatibleCategorySlugs.includes(category.slug)?form.compatibleCategorySlugs.filter((slug)=>slug!==category.slug):[...form.compatibleCategorySlugs,category.slug]})}/>{category.name}</label>)}</fieldset>:null}{message?<KgdStatus message={message} error/>:null}<div className="kgd-form-actions"><button className="kgd-button" type="button" onClick={onClose}>Close</button><button className="kgd-button is-primary" type="submit">Save service</button></div></form></KgdModal>;
}

function CategoryForm({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState('');const [description,setDescription]=useState('');const [message,setMessage]=useState('');async function submit(event:FormEvent){event.preventDefault();try{await apiFetch('/api/admin/service-categories',{method:'POST',body:JSON.stringify({name,description})});onSaved();}catch(error){setMessage(error instanceof ApiError?error.message:'Category could not be created.');}}return <KgdModal title="New category" onClose={onClose}><form className="kgd-form" onSubmit={submit}><label><span>Name</span><input value={name} onChange={(event)=>setName(event.target.value)} required/></label><label><span>Description</span><textarea value={description} onChange={(event)=>setDescription(event.target.value)}/></label>{message?<KgdStatus message={message} error/>:null}<div className="kgd-form-actions"><button className="kgd-button" type="button" onClick={onClose}>Close</button><button className="kgd-button is-primary" type="submit">Create category</button></div></form></KgdModal>}
