import { Download, LogOut } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { ApiError, apiFetch } from '../../lib/api';
import type { KgdUser } from '../KgdApp';
import { dateTime, KgdPage, KgdStatus } from '../components';

type Settings = {
  business: { name: string; email: string | null; phone: string | null; address_line_1: string | null; city: string | null; postcode: string | null; country: string | null; timezone: string };
  booking: { minimum_notice_hours: number; maximum_advance_days: number; buffer_minutes: number; cancellation_cutoff_hours: number; deposit_pence: number; tax_set_aside_percent: number };
  auditLogs: Array<{ action: string; entity_type: string; metadata: Record<string, unknown>; created_at: string }>;
};

export function SettingsPage({ user, onLogout }: { user: KgdUser; onLogout: () => void }) {
  const [data, setData] = useState<Settings | null>(null);
  const [business, setBusiness] = useState({ name: '', email: '', phone: '', addressLine1: '', city: '', postcode: '', country: '', timezone: 'Europe/London' });
  const [booking, setBooking] = useState({ minimumNoticeHours: 2, maximumAdvanceDays: 120, bufferMinutes: 15, cancellationCutoffHours: 24, deposit: '15', taxSetAsidePercent: 20 });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { apiFetch<Settings>('/api/admin/settings').then((result) => { setData(result); setBusiness({ name: result.business.name, email: result.business.email ?? '', phone: result.business.phone ?? '', addressLine1: result.business.address_line_1 ?? '', city: result.business.city ?? '', postcode: result.business.postcode ?? '', country: result.business.country ?? '', timezone: result.business.timezone }); setBooking({ minimumNoticeHours: result.booking.minimum_notice_hours, maximumAdvanceDays: result.booking.maximum_advance_days, bufferMinutes: result.booking.buffer_minutes, cancellationCutoffHours: result.booking.cancellation_cutoff_hours, deposit: String(result.booking.deposit_pence / 100), taxSetAsidePercent: result.booking.tax_set_aside_percent }); }).catch((requestError) => setError(requestError instanceof ApiError ? requestError.message : 'Settings could not be loaded.')); }, []);
  async function saveBusiness(event: FormEvent) { event.preventDefault(); setMessage(''); try { await apiFetch('/api/admin/settings/business', { method: 'PATCH', body: JSON.stringify(business) }); setMessage('Business settings saved.'); } catch (requestError) { setError(requestError instanceof ApiError ? requestError.message : 'Business settings could not be saved.'); } }
  async function saveBooking(event: FormEvent) { event.preventDefault(); setMessage(''); try { await apiFetch('/api/admin/settings/booking', { method: 'PATCH', body: JSON.stringify({ ...booking, depositPence: Math.round(Number(booking.deposit) * 100) }) }); setMessage('Booking settings saved.'); } catch (requestError) { setError(requestError instanceof ApiError ? requestError.message : 'Booking settings could not be saved.'); } }
  return <KgdPage eyebrow="CONTROL CENTRE" title="Settings">
    {error ? <KgdStatus message={error} error /> : null}{message ? <KgdStatus message={message} /> : null}
    <div className="kgd-settings-layout"><section className="kgd-section"><header><div><p className="kgd-eyebrow">BUSINESS</p><h2>Business details</h2></div></header><form className="kgd-form" onSubmit={saveBusiness}><div className="kgd-form-grid"><label><span>Name</span><input value={business.name} onChange={(event) => setBusiness({ ...business, name: event.target.value })} required /></label><label><span>Email</span><input type="email" value={business.email} onChange={(event) => setBusiness({ ...business, email: event.target.value })} /></label><label><span>Phone</span><input value={business.phone} onChange={(event) => setBusiness({ ...business, phone: event.target.value })} /></label><label><span>Address</span><input value={business.addressLine1} onChange={(event) => setBusiness({ ...business, addressLine1: event.target.value })} /></label><label><span>City</span><input value={business.city} onChange={(event) => setBusiness({ ...business, city: event.target.value })} /></label><label><span>Postcode</span><input value={business.postcode} onChange={(event) => setBusiness({ ...business, postcode: event.target.value })} /></label><label><span>Country</span><input value={business.country} onChange={(event) => setBusiness({ ...business, country: event.target.value })} /></label><label><span>Timezone</span><input value={business.timezone} onChange={(event) => setBusiness({ ...business, timezone: event.target.value })} required /></label></div><button className="kgd-button is-primary" type="submit">Save business</button></form></section>
      <section className="kgd-section"><header><div><p className="kgd-eyebrow">BOOKING</p><h2>Booking rules</h2></div></header><form className="kgd-form" onSubmit={saveBooking}><div className="kgd-form-grid"><label><span>Minimum notice (hours)</span><input type="number" min="0" value={booking.minimumNoticeHours} onChange={(event) => setBooking({ ...booking, minimumNoticeHours: Number(event.target.value) })} /></label><label><span>Maximum advance (days)</span><input type="number" min="1" value={booking.maximumAdvanceDays} onChange={(event) => setBooking({ ...booking, maximumAdvanceDays: Number(event.target.value) })} /></label><label><span>Buffer time (minutes)</span><input type="number" min="0" step="5" value={booking.bufferMinutes} onChange={(event) => setBooking({ ...booking, bufferMinutes: Number(event.target.value) })} /></label><label><span>Cancellation cutoff (hours)</span><input type="number" min="0" value={booking.cancellationCutoffHours} onChange={(event) => setBooking({ ...booking, cancellationCutoffHours: Number(event.target.value) })} /></label><label><span>Deposit amount (£)</span><input type="number" min="0" step="0.01" value={booking.deposit} onChange={(event) => setBooking({ ...booking, deposit: event.target.value })} /></label><label><span>Tax set-aside (%)</span><input type="number" min="0" max="100" value={booking.taxSetAsidePercent} onChange={(event) => setBooking({ ...booking, taxSetAsidePercent: Number(event.target.value) })} /></label></div><button className="kgd-button is-primary" type="submit">Save booking rules</button></form></section>
      <PasswordPanel email={user.email} onSaved={() => setMessage('Password changed.')} />
      <section className="kgd-section"><header><div><p className="kgd-eyebrow">DATA</p><h2>Exports & privacy</h2></div></header><div className="kgd-stack-actions"><a className="kgd-button" href="/api/admin/clients/export.csv"><Download size={16} />Export clients CSV</a><a className="kgd-button" href="/api/admin/finances/export.csv"><Download size={16} />Export finances CSV</a></div><p className="kgd-help">Client profiles contain the permanent GDPR anonymisation control. Anonymised booking and finance records remain for reporting.</p></section>
      <section className="kgd-section kgd-settings-wide"><header><div><p className="kgd-eyebrow">AUDIT LOG</p><h2>Recent owner actions</h2></div></header>{data?.auditLogs.length ? <div className="kgd-list">{data.auditLogs.map((log, index) => <div className="kgd-list-row is-compact" key={`${log.created_at}-${index}`}><span><strong>{log.action.replace(/\./g, ' ')}</strong><small>{log.entity_type}</small></span><time>{dateTime(log.created_at)}</time></div>)}</div> : <p className="kgd-empty">No owner actions recorded yet.</p>}</section>
      <div className="kgd-settings-wide"><button className="kgd-button is-danger" type="button" onClick={onLogout}><LogOut size={16} />Log out</button></div>
    </div>
  </KgdPage>;
}

function PasswordPanel({ email, onSaved }: { email: string; onSaved: () => void }) {
  const [form, setForm] = useState({ currentPassword: '', newPassword: '' }); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); try { await apiFetch('/api/auth/change-password', { method: 'POST', body: JSON.stringify(form) }); setForm({ currentPassword: '', newPassword: '' }); setError(''); onSaved(); } catch (requestError) { setError(requestError instanceof ApiError ? requestError.message : 'Password could not be changed.'); } }
  return <section className="kgd-section"><header><div><p className="kgd-eyebrow">SECURITY</p><h2>Owner access</h2></div></header><p className="kgd-help">Signed in as {email}</p><form className="kgd-form" onSubmit={submit}><label><span>Current password</span><input type="password" autoComplete="current-password" value={form.currentPassword} onChange={(event) => setForm({ ...form, currentPassword: event.target.value })} required /></label><label><span>New password</span><input type="password" autoComplete="new-password" minLength={12} value={form.newPassword} onChange={(event) => setForm({ ...form, newPassword: event.target.value })} required /></label>{error ? <KgdStatus message={error} error /> : null}<button className="kgd-button" type="submit">Change password</button></form></section>;
}
